name: Node Continuous Integration

on:
  pull_request:
    branches: [ ci-cd ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci # similar to npm install (ci = clean install) but used in automated environments
      - run: npm test